### ISSUE TITLE
SDBG breaks eclipse

### ISSUE THREAD

**Issue by straaand** [sdbg/sdbg#176]
Hi,

I cannot use the latest SDBG version with my setup (Eclipse 2023-03, Ubuntu 22.04) since it breaks Eclipse.
This is the output from the Eclipse error log:
```
!ENTRY com.github.sdbg.debug.core 4 0 2023-06-02 13:35:53.349
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in com.github.sdbg.debug.core.SDBGDebugCorePlugin.stop() of bundle com.github.sdbg.debug.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:895)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.sdbg.debug.core.internal.browser.BrowserManager.dispose()" because "com.github.sdbg.debug.core.configs.ChromeLaunchConfigurationDelegate.browserManager" is null
	at com.github.sdbg.debug.core.configs.ChromeLaunchConfigurationDelegate.dispose(ChromeLaunchConfigurationDelegate.java:75)
	at com.github.sdbg.debug.core.SDBGDebugCorePlugin.stop(SDBGDebugCorePlugin.java:392)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	... 13 more
Root exception:
java.lang.NullPointerException: Cannot invoke "com.github.sdbg.debug.core.internal.browser.BrowserManager.dispose()" because "com.github.sdbg.debug.core.configs.ChromeLaunchConfigurationDelegate.browserManager" is null
	at com.github.sdbg.debug.core.configs.ChromeLaunchConfigurationDelegate.dispose(ChromeLaunchConfigurationDelegate.java:75)
	at com.github.sdbg.debug.core.SDBGDebugCorePlugin.stop(SDBGDebugCorePlugin.java:392)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by keinhaar** [comment]
What do you mean by "it breaks Eclipse"? Is eclipse no longer usable???
Just installed a fresh eclipse 2023-03 version from "eclipse.org" on debian linux and installed SDBG from "https://sdbg.github.io/p2".
Eclipse starts just fine, and SDBG plugin is loaded and seems to work normally.
Please give some more information about what you tried to do. I expect there will be a problem with the browser detection. 
do you have set CHROME_LOCATION or BROWSER_LOCATION? 
do you have chrome or chromium installed?
what launcher did you run?

**Comment by keinhaar** [comment]
No feedback after 3 months. 
Closing now, because it works.
